# Site settings
title: CIB | Capital Investments @ Berkeley
email: sumeetjain@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    We are Capital Investments at Berkeley, an student run hedge fund. We manage over 5000 dollars every semester.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cibberkeley.com" # the base hostname & protocol for your site
twitter_username: sumeezy
github_username: sumeet-jain 

# Build settings
markdown: kramdown
